### DISCUSSION TITLE
راه‌اندازی phpMyAdmin به صورت HTTPS با Caddy

### DISCUSSION THREAD

**Discussion by Netazad22** [Gozargah/Marzban#1581] [Show and tell]
سلام دوستان،  
امیدوارم حالتون خوب باشه.

اگر از phpMyAdmin استفاده می‌کنید، احتمالا متوجه شدید که به‌طور پیش‌فرض HTTPS فعال نیست که این می‌تونه یه مشکل امنیتی باشه.

برای فعال کردن SSL در phpMyAdmin راه‌های مختلفی هست (مثل Nginx، HAProxy و ...) که در داکیومنت مرزبان هم آموزشی هست که می‌تونید از [اینجا](https://gozargah.github.io/marzban/fa/examples/mysql#%D8%B1%D8%A7%D9%87%E2%80%8C%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-phpmyadmin-%D8%A8%D9%87-%D8%B5%D9%88%D8%B1%D8%AA-https) ببینید. ولی چون من از Caddy استفاده می‌کنم و آموزش خاصی پیدا نکردم، خودم این کار رو انجام دادم و گفتم با شما به اشتراک بذارم.

من توی این آموزش فرض رو بر این می‌ذارم که شما Caddy رو نصب ندارید و می‌خواید تازه نصبش کنید.

---

### 1. ویرایش فایل `docker-compose.yml`

اول باید فایل `docker-compose.yml` مرزبان رو ادیت کنید. برای این کار دستور زیر رو توی ترمینال وارد کنید:

```bash
sudo nano /opt/marzban/docker-compose.yml
```

بعد باید برید پایین صفحه و این بخش رو به آخر فایل اضافه کنید:

```yaml
caddy:
  image: caddy:latest
  restart: always
  network_mode: host
  ports:
    - 80:80
    - 443:443
    - 8585:8585
  volumes:
    - /var/lib/marzban:/var/lib/marzban
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_volume:/data
    - caddy_volume:/config

volumes:
  caddy_volume:
```

وقتی اینارو نوشتید با `Ctrl + S` می تونید فایل رو ذخیره کنید و بعد با `Ctrl + X` از ویرایشگر خارج شید.

---

### 2. تنظیمات نهایی فایل `docker-compose.yml`

حالا فایل `docker-compose.yml` باید شبیه به این باشه:

```yaml
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - /var/lib/marzban/logs:/var/lib/marzban-node
    depends_on:
      - caddy
      - mariadb

  mariadb:
    image: mariadb:lts
    env_file: .env
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /var/lib/marzban/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: .env
    network_mode: host
    environment:
      PMA_HOST: 127.0.0.1
      APACHE_PORT: 4090
      UPLOAD_LIMIT: 1024M
    depends_on:
      - mariadb

  caddy:
    image: caddy:latest
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 8585:8585
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_volume:/data
      - caddy_volume:/config

volumes:
  caddy_volume:
```

**توجه:**  
اگر به‌جای **MariaDB** از **MySQL** استفاده می‌کنید، این تنظیمات ممکنه کمی فرق داشته باشه. پیشنهاد می‌کنم کدها رو کپی پیست نکنید و با کدهای خودتون مقایسه کنید.

---

#### 3. ساخت و ویرایش فایل `Caddyfile`

حالا باید یه فایل به اسم `Caddyfile` بسازید و اون رو ویرایش کنید. برای این کار دستور زیر رو وارد کنید:

```bash
sudo nano /opt/marzban/Caddyfile
```

حالا داخل این فایل، به‌جای `yourpaneldomain.com` و `yoursubscriptiondomain.com` دامنه‌های خودتون رو بذارید. اینطور باید باشه:

```plaintext
yourpaneldomain.com {
    reverse_proxy /* unix//var/lib/marzban/marzban.socket
}

yourpaneldomain.com:8585 {
    reverse_proxy 127.0.0.1:4090
}

yoursubscriptiondomain.com {
    reverse_proxy unix//var/lib/marzban/marzban.socket
}
```
وقتی اینارو نوشتید با `Ctrl + S` می تونید فایل رو ذخیره کنید و بعد با `Ctrl + X` از ویرایشگر خارج شید.

**توجه:**
- به‌جای `4090`، پورتی که برای phpmyadmin خودتون در نظر گرفتید استفاده کنید.
- به‌جای `yourpaneldomain.com`، دامنه‌ای که می‌خواهید برای پنلتون استفاده کنید رو وارد کنید.
- به‌جای `yoursubscriptiondomain.com`، دامنه‌ای که می‌خواهید برای سابسکریپشن استفاده کنید رو بذارید.

---

#### 4. ویرایش فایل `.env`

قبل از اینکه مرزبان رو ریستارت کنید، باید دو تا متغیر رو توی فایل `.env` تنظیم کنید.

برای این کار دستور زیر رو وارد کنید:

```bash
sudo nano /opt/marzban/.env
```

بعد این دو خط رو اضافه کنید:

```plaintext
UVICORN_UDS = /var/lib/marzban/marzban.socket
XRAY_SUBSCRIPTION_URL_PREFIX = https://YOUR_DOMAIN
```

**توجه:**  
- به‌جای `YOUR_DOMAIN` دامنه‌ای که می‌خواهید برای سابسکریپشن استفاده کنی رو وارد کن (مثلاً `yoursubscriptiondomain.com`).

بعد از اینکه اینارو نوشتید، فایل رو با `Ctrl + S` ذخیره کنید و بعد با `Ctrl + X` از ویرایشگر خارج شوید.

---

#### 5. ریستارت کردن مرزبان

حالا وقتشه که مرزبان رو ریستارت کنید تا تغییرات اعمال بشه. برای این کار دستور زیر رو وارد کنید:

```bash
marzban restart
```

---

#### 6. دسترسی به پنل PHPMyAdmin

بعد از ریستارت مرزبان، می‌تونید با این آدرس به پنل PHPMyAdmin دسترسی پیدا کنید:

```
https://panel.marzban.com:8585
```

---

 اگر سوالی داشتید، خوشحال میشم کمک کنم.
