### ISSUE TITLE
502 Bad Gateway after update from v0.6.0 to v0.7.0

### ISSUE THREAD

**Issue by SegaSh99** [Gozargah/Marzban#1400]
I use docker and set up docker compose config with Marzban and Traefik Proxy. On Marzban version 0.6.0 everything works, but after upgrading to version 0.7.0 I get an error
I also used Nginx, which also returns an error
When trying to open the image URL directly (http://172.18.0.4:8000/), I got HTTP ERROR 502

**Machine details (please complete the following information):**
 - OS: Ubuntu 22.04
- Docker Compose version v2.27.0

**Comment by atomexpert** [comment]
> I use docker and set up docker compose config with Marzban and Traefik Proxy. On Marzban version 0.6.0 everything works, but after upgrading to version 0.7.0 I get an error I also used Nginx, which also returns an error When trying to open the image URL directly (http://172.18.0.4:8000/), I got HTTP ERROR 502
> 
> **Machine details (please complete the following information):**
> 
> * OS: Ubuntu 22.04
> * Docker Compose version v2.27.0

Same problem. After installation the panel does not work

**Comment by PrevikYT** [comment]
so, how can i downgrade my panel

**Comment by SegaSh99** [comment]
> People are you reading logs sometimes?
> 
> Since 0.7 release you need HTTPS (SSL) connection to panel to open it. It won't work anymore without secure connection. With https everything works great, including nginx. Buy some domain, use certbot and enjoy)

![image](https://github.com/user-attachments/assets/5c5f2012-5b08-46af-85c1-8a2b03ca78a0)

nginx-1    | 2024/10/27 11:18:28 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.3, server: , request: "GET /dashboard HTTP/1.1", upstream: "http://172.19.0.2:8000/dashboard", host: "marzban.vpn.my-domain.ru"

**Comment by SegaSh99** [comment]
> Provide nginx & marzban .env

nginx:
```
server {
    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://marzban:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-SSL on;
    }
}
``` 

.env: The rest of the variables are default (not changed)
```
# Main
# ----
PROJECT_NAME=marzban
DOMAIN=vpn.my-domain.ru

# Docker
# ------
COMPOSE_FILE=docker-compose.yml
DOCKER_MYSQL_PORT=12222

# MySQL
# ---------
MYSQL_DATABASE=marzban
MYSQL_USER=vpn
MYSQL_PASSWORD=vpn
MYSQL_ROOT_PASSWORD=vpn


# Web server configuration
UVICORN_HOST=0.0.0.0
UVICORN_PORT=8000

## We highly recommend add admin using `marzban cli` tool and do not use
## the following variables which is somehow hard codded infrmation.
SUDO_USERNAME="login"
SUDO_PASSWORD="pass"
```

docker compose:
```
services:
  traefik:
    image: traefik:3
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/data/traefik.yml:/traefik.yml:ro
      - ./traefik/data/acme.json:/acme.json
      - ./traefik/configurations:/configurations:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-traefik.service=api@internal"
      - "traefik.http.routers.${PROJECT_NAME}-traefik.middlewares=user-auth@file"
      - "traefik.http.routers.${PROJECT_NAME}-traefik.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-traefik.tls.certresolver=letsEncrypt"
    networks:
      - vpn
    ports:
      - "80:80"
      - "443:443"

  nginx:
    image: nginx:1.27-alpine
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.rule=Host(`marzban.${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.tls.certresolver=letsEncrypt"
    depends_on:
      - traefik
    networks:
      - vpn

  marzban:
    image: gozargah/marzban:latest
    restart: on-failure
    env_file: .env
    volumes:
      - /var/lib/marzban:/var/lib/marzban
    networks:
      - vpn

networks:
  vpn:
    driver: bridge
```
I added Nginx as an experiment, but you can directly direct traffic to the marzban container
Both options do not work on version 0.7.0
https://traefik.vpn.my-domain.ru - is work

**Comment by SegaSh99** [comment]
> First of all, port 80 is for plain http, NOT HTTPS!
> Second - where did you get `http://marzban` host? Why? What for?
> It's just simple like `http://127.0.0.1:8000`


http://marzban - This is the name of the container that needs to be proxy the request.
Nginx is inside the container, so it works with port 80
Port 443 accepts traefik and forwards it to the container

**Comment by SegaSh99** [comment]
> And you don't need this `DOMAIN=vpn.my-domain.ru` if you use NGINX ssl config! And I hope you are not really using `my-domain.ru` because it's from some example and not for real use

SSL is set by traefik, not nginx

**Comment by SegaSh99** [comment]
I downgraded to 0.6.0 and everything worked
So don't write that my config is not working if you don't understand it

![image](https://github.com/user-attachments/assets/2b169c22-4616-475c-9777-e674c24ed616)

**Comment by SegaSh99** [comment]
Мне нужна комбинация traefik + marzban, без всяких nginx и прочего

**Comment by M03ED** [comment]
add this to your marzban docker file 
```yml
    ports:
      - "127.0.0.1:3333:3333"
```
change port to your dashboard port

**Comment by M03ED** [comment]
and use 127.0.0.1 instead on 172.*

**Comment by ivanik7** [comment]
Is there any way to disable SSL enforcing? Same problem with my traefik setup. I want env variable that will revert this behavior.
I just want to use Traefik for all ssl stuff. 

@SerGioPicconti 
> Значит нужно настроить верно проксификацию 443 порта в траефике. 80 порт тут не нужен вообще

If traefik inside docker it can not connect to http://172.17.0.1:8000 beacuse marzban not listing to this ip

**Comment by yaramahmadi** [comment]
> ```yaml
>     ports:
>       - "127.0.0.1:3333:3333"
> ```

I tried this solution, but it didn’t work for me. 

Thank you.

**Comment by M03ED** [comment]
map this file to your docker
something like this:
then you should be able to use 172 range as uvicorn host
if this worked i will merge it 

```yml
volumes:
  - /var/lib/marzban:/var/lib/marzban   
  - /opt/marzban/main.py:/code/main.py
```

```python
import click
import logging
import os
import ssl
import ipaddress

import uvicorn
from cryptography import x509
from cryptography.hazmat.backends import default_backend

from app import app, logger
from config import (DEBUG, UVICORN_HOST, UVICORN_PORT, UVICORN_SSL_CERTFILE,
                    UVICORN_SSL_KEYFILE, UVICORN_UDS)


def check_and_modify_ip(ip_address: str) -> str:
    """
    Check if an IP address is private. If not, return localhost.

    IPv4 Private range = [
        "192.168.0.0",
        "192.168.255.255",
        "10.0.0.0",
        "10.255.255.255",
        "172.16.0.0",
        "172.31.255.255"
    ]

    Args:
        ip_address (str): IP address to check

    Returns:
        str: Original IP if private, otherwise localhost

    Raises:
        ValueError: If the provided IP address is invalid, return localhost.
    """
    try:
        # Convert string to IP address object
        ip = ipaddress.ip_address(ip_address)

        if ip.is_private:
            return ip_address
        else:
            return "localhost"

    except ValueError as e:
        return "localhost"


def validate_cert_and_key(cert_file_path, key_file_path):
    if not os.path.isfile(cert_file_path):
        raise ValueError(
            f"SSL certificate file '{cert_file_path}' does not exist.")
    if not os.path.isfile(key_file_path):
        raise ValueError(f"SSL key file '{key_file_path}' does not exist.")

    try:
        context = ssl.create_default_context()
        context.load_cert_chain(certfile=cert_file_path, keyfile=key_file_path)
    except ssl.SSLError as e:
        raise ValueError(f"SSL Error: {e}")

    try:
        with open(cert_file_path, 'rb') as cert_file:
            cert_data = cert_file.read()
            cert = x509.load_pem_x509_certificate(cert_data, default_backend())

        if cert.issuer == cert.subject:
            raise ValueError(
                "The certificate is self-signed and not issued by a trusted CA.")

    except Exception as e:
        raise ValueError(f"Certificate verification failed: {e}")


if __name__ == "__main__":
    # Do NOT change workers count for now
    # multi-workers support isn't implemented yet for APScheduler and XRay module

    bind_args = {}

    if UVICORN_SSL_CERTFILE and UVICORN_SSL_KEYFILE:
        validate_cert_and_key(UVICORN_SSL_CERTFILE, UVICORN_SSL_KEYFILE)

        bind_args['ssl_certfile'] = UVICORN_SSL_CERTFILE
        bind_args['ssl_keyfile'] = UVICORN_SSL_KEYFILE

        if UVICORN_UDS:
            bind_args['uds'] = UVICORN_UDS
        else:
            bind_args['host'] = UVICORN_HOST
            bind_args['port'] = UVICORN_PORT

    else:
        if UVICORN_UDS:
            bind_args['uds'] = UVICORN_UDS
        else:

            ip = check_and_modify_ip(UVICORN_HOST)

            logger.warning(f"""
{click.style('IMPORTANT!', blink=True, bold=True, fg="yellow")}
You're running Marzban without specifying {click.style('UVICORN_SSL_CERTFILE', italic=True, fg="magenta")} and {click.style('UVICORN_SSL_KEYFILE', italic=True, fg="magenta")}.
The application will only be accessible through localhost. This means that {click.style('Marzban and subscription URLs will not be accessible externally', bold=True)}.

If you need external access, please provide the SSL files to allow the server to bind to 0.0.0.0. Alternatively, you can run the server on localhost or a Unix socket and use a reverse proxy, such as Nginx or Caddy, to handle SSL termination and provide external access.

If you wish to continue without SSL, you can use SSH port forwarding to access the application from your machine. note that in this case, subscription functionality will not work. 

Use the following command:

{click.style(f'ssh -L {UVICORN_PORT}:localhost:{UVICORN_PORT} user@server', italic=True, fg="cyan")}

Then, navigate to {click.style(f'http://{ip}:{UVICORN_PORT}', bold=True)} on your computer.
            """)

            bind_args['host'] = ip
            bind_args['port'] = UVICORN_PORT

    if DEBUG:
        bind_args['uds'] = None
        bind_args['host'] = '0.0.0.0'

    try:
        uvicorn.run(
            "main:app",
            **bind_args,
            workers=1,
            reload=DEBUG,
            log_level=logging.DEBUG if DEBUG else logging.INFO
        )
    except FileNotFoundError:  # to prevent error on removing unix sock
        pass
```

**Comment by M03ED** [comment]
if nobody want to test this i can close issue

**Comment by yaramahmadi** [comment]
> if nobody want to test this i can close issue

I'll test it and let you know within the next hour.

**Comment by MaverickTse** [comment]
I'm having the same problem and method 3 does not work for me. Running NPM and Marzban with Dockge.

**Marzban compose file:**
```yaml
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - ./lib/marzban:/var/lib/marzban
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/nginx_proxy_manager/letsencrypt/archive:/var/lib/marzban/certs
networks: {}
```
**.env file**
```
UVICORN_PORT = 8443
UVICORN_UDS: "/var/run/docker.socket"
UVICORN_SSL_CERTFILE = "/var/lib/marzban/certs/npm-1/fullchain1.pem"
UVICORN_SSL_KEYFILE = "/var/lib/marzban/certs/npm-1/privkey1.pem"
XRAY_SUBSCRIPTION_URL_PREFIX = https://xui.example.com
```
**NPM setting**
![image](https://github.com/user-attachments/assets/4536d4ce-9e77-43cb-aaf8-574c4f8fbddf)

![image](https://github.com/user-attachments/assets/fb1b1511-8845-40df-b829-98886e517025)

![image](https://github.com/user-attachments/assets/400d2343-2b48-46c5-ad38-e6b82f949c45)

Tried switching between HTTP and HTTPS but didn't make a difference

**Comment by anti1304** [comment]
Hello everyone, I rolled back the marzban version to 0.6.0 but when I upload an old backup to /opt/marzban it is automatically updated, what should I do?

**Comment by anti1304** [comment]
> > Итак, как я могу понизить версию своей панели?
> 
> Вы можете установить определенную версию, если хотите. `bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install v0.6.0`

Does this no longer work?

root@v211739:~# bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install v0.6.0
Unknown option: v0.6.0

**Comment by maolei133** [comment]
> if nobody want to test this i can close issue

I tested your code above, and now NPM can connect to the Docker container by configuring port forwarding. Please submit the code to fix the bug.

`
  marzban:
    image: gozargah/marzban:v0.7.0
    container_name: marzban_container
    environment:
      - SUDO_USERNAME="admin"
      - SUDO_PASSWORD="123456789000"
    volumes:
      - ./data/marzban:/var/lib/marzban
      - ./data/main.py:/code/main.py
`
`
  nginx-proxy-manager:
    container_name: nginx_container
    image: chishin/nginx-proxy-manager-zh:2.12.1
    ports:
      - "50080:80"
      - "50443:443"
      - "50081:81"
      - "50100-50109:50100-50109"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
`
![image](https://github.com/user-attachments/assets/a07fc074-9e33-4943-b5f8-0367c50397ca)
![image](https://github.com/user-attachments/assets/fb1083fc-cfdd-4d80-a2fd-d5dc1b8730b5)

**Comment by fractalshine** [comment]
Hello. I think it's kinda related. Trying to update from 0.6.0 to latest tag (0.8.4 for now). Marzban panel behind nginx proxy with ssl. After upgrade I've got 502 in browser, trying to connect rhtough nginx and "The connection was reset" when port mapped though ssh. On my vps can't curl even curl to mapped container (127.0.0.1:9000) - "curl: (56) Recv failure: Connection reset by peer". The only way to connect is - from inside container.
Part of my docker-compose.yml
```
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
      #network_mode: host
    ports:
      - "127.0.0.1:9000:8000"
      - "127.0.0.1:8090:8080"
    volumes:
      - /var/lib/marzban-tests:/var/lib/marzban
    depends_on:
      - mysql
```
