### ISSUE TITLE
Настройка времени

### ISSUE THREAD

**Issue by MaxTheFirst** [Gozargah/Marzban#1626]
Здравствуйте! Не подскажите, как синхронизировать время в контейнере с серверым временем? 
Просто я пробовал менять docker_compose.yaml:

```
version: '3.8'

services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - /etc/localtime:/etc/localtime:ro
 
```
Но это не помогло...
