### ISSUE TITLE
Ports exposed via docker port doesn't accessible

### ISSUE THREAD

**Issue by fractalshine** [Gozargah/Marzban#1638]
**Describe the bug**
Panel doesn't accessible if ports mapped via 'port' directive

**To Reproduce**
Update from 0.6.0 to latest tag (0.8.4 for now). Marzban panel behind nginx proxy with ssl. After upgrade I've got 502 in browser, trying to connect through nginx and "The connection was reset" when port mapped though ssh. On my vps can't curl even curl to mapped localhost container (127.0.0.1:9000) - "curl: (56) Recv failure: Connection reset by peer". The only way to connect is - from inside container.
Part of my docker-compose.yml

```
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
      #network_mode: host
    ports:
      - "127.0.0.1:9000:8000"
      - "127.0.0.1:8090:8080"
    volumes:
      - /var/lib/marzban-tests:/var/lib/marzban
    depends_on:
      - mysql
   ```

**Additional context**
I assume [this](https://github.com/Gozargah/Marzban/issues/1400#issuecomment-2441082294) code has to be in upstream.
