### ISSUE TITLE
cli import-from-env requires discord and telegram configs to modify existing admin

### ISSUE THREAD

**Issue by mihett05** [Gozargah/Marzban#1659]
**Describe the bug**
When you try to sync already existing admin with env it requires telegram_id and discord_webhook to be provided in AdminPartialModify

**To Reproduce**
1. Install xray
2. Clone marzban
3. Create venv and install requirements
4. Run migrations
5. Run `marzban-cli admin import-from-env -y` first time
6. Run import-from-env second-time

**Expected behavior**
Marzban should sync with admin without pydantic validation errors

**Screenshots**
```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/marzban/code/cli/admin.py:209 in import_from_env                                            │
│                                                                                                  │
│   206 │   │   │   admin = crud.partial_update_admin(                                             │
│   207 │   │   │   │   db,                                                                        │
│   208 │   │   │   │   current_admin,                                                             │
│ ❱ 209 │   │   │   │   AdminPartialModify(password=password, is_sudo=True)                        │
│   210 │   │   │   )                                                                              │
│   211 │   │   # If env admin does not exist yet                                                  │
│   212 │   │   else:                                                                              │
│                                                                                                  │
│ ╭───────────────────────────────── locals ──────────────────────────────────╮                    │
│ │         admin = None                                                      │                    │
│ │ current_admin = <app.db.models.Admin object at 0x7fdaa02dd7d0>            │                    │
│ │            db = <sqlalchemy.orm.session.Session object at 0x7fdaa00c8190> │                    │
│ │      password = '...'                                                     │                    │
│ │      username = 'admin'                                                   │                    │
│ │    yes_to_all = True                                                      │                    │
│ ╰───────────────────────────────────────────────────────────────────────────╯                    │
│                                                                                                  │
│ /var/marzban/code/.venv/lib/python3.11/site-packages/pydantic/main.py:214 in __init__            │
│                                                                                                  │
│    211 │   │   """                                                                               │
│    212 │   │   # `__tracebackhide__` tells pytest and some other tools to omit this function fr  │
│    213 │   │   __tracebackhide__ = True                                                          │
│ ❱  214 │   │   validated_self = self.__pydantic_validator__.validate_python(data, self_instance  │
│    215 │   │   if self is not validated_self:                                                    │
│    216 │   │   │   warnings.warn(                                                                │
│    217 │   │   │   │   'A custom validator is returning a value other than `self`.\n'            │
│                                                                                                  │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮                     │
│ │ data = {'password': '...', 'is_sudo': True}                              │                     │
│ │ self = AdminPartialModify()                                              │                     │
│ ╰──────────────────────────────────────────────────────────────────────────╯                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 2 validation errors for AdminPartialModify
telegram_id
  Field required [type=missing, input_value={'password': '...', 'is_sudo': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
discord_webhook
  Field required [type=missing, input_value={'password': '...', 'is_sudo': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
```

**Machine details (please complete the following information):**
 - OS: debian 12
- Python version: 3.11
- Nodejs version: N/A
- Browser N/A

**Additional context**
I'm trying to deploy marzban using ansible without docker and I need to use marzban api with my app through UDS. This is why I need them to run in a one VM/container

**Comment by ImMohammad20000** [comment]
you didn't add any env admin use env if you are a developer and you know what you do

**Comment by mihett05** [comment]
> you didn't add any env admin use env if you are a developer and you know what you do

I've provided SUDO_USERNAME and SUDO_PASSWORD through setting env variables
Here is part of ansible playbook which fails
```yaml
- name: Clone marzban
      ansible.builtin.git:
        repo: https://github.com/Gozargah/Marzban.git
        dest: "/var/marzban/code"
        version: master
        clone: true
      register: repo_clone
      failed_when:
        - repo_clone.failed
        - not "Local modifications exist" in repo_clone.msg
      environment:
        GIT_TERMINAL_PROMPT: 0
    - name: Copy xray config
      ansible.builtin.copy:
        src: ./xray_config.json
        dest: "/var/marzban/code/xray_config.json"
        mode: "0755"
    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: "/var/marzban/code/requirements.txt"
        virtualenv: "/var/marzban/code/.venv"
        virtualenv_python: python3
    - name: Run migrations
      ansible.builtin.shell:
        cmd: "/var/marzban/code/.venv/bin/python3 -m alembic upgrade head > .migrations.txt"
        chdir: "/var/marzban/code"
        creates: .migrations.txt
    - name: Create marzban admin
      ansible.builtin.shell:
        cmd: "/var/marzban/code/.venv/bin/python3 /var/marzban/code/marzban-cli.py admin import-from-env -y > .admin.txt"
        chdir: "/var/marzban/code"
        creates: "/var/marzban/code/.admin.txt"
      environment:
        SUDO_USERNAME: "{{ username }}"
        SUDO_PASSWORD: "{{ password }}"
```
