### ISSUE TITLE
Is it possible to run Home page and VLESS on port 443?

### ISSUE THREAD

**Issue by fastblink** [Gozargah/Marzban#1701]
I want to run Home page and VLESS on port 443. I want when my users open a subscription link to open a link without a port, example `https://mysite.com/subscription/***`. And when they open Home page to open a link without a port, example `https://mysite.com***`
My .env is:
```
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 443
```
/opt/marzban/docker-compose.yml is:
```
services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    env_file: .env
    volumes:
      - /opt/marzban/templates/subscription:/code/app/templates/subscription
      - /opt/marzban/templates/home:/code/app/templates/home
      - /var/lib/marzban:/var/lib/marzban
      - /etc/letsencrypt/live/fast-blink.com/fullchain.pem:/var/lib/marzban/certs/mysite.com/fullchain.pem 
      - /etc/letsencrypt/live/fast-blink.com/privkey.pem:/var/lib/marzban/certs/mysite.com/privkey.pem   
    network_mode: host
```

config is:
```
"inbounds": [
 {
      "tag": "vless",
      "port": 443,
      "protocol": "vless",
   
    }
  ]
```
When I start marzban, then Xray core always Restarting :
```
[+] Running 1/1
 ✔ Container marzban  Started                                                                                                                                0.2s 
marzban  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban  | INFO:     Started server process [1]
marzban  | INFO:     Waiting for application startup.
marzban  | INFO:     Generating Xray core config
marzban  | INFO:     Xray core config generated in 0.06 seconds
marzban  | INFO:     Starting main Xray core
marzban  | WARNING:  Xray core 24.12.31 started
marzban  | INFO:     Starting nodes Xray core
marzban  | INFO:     Application startup complete.
marzban  | INFO:     Uvicorn running on https://0.0.0.0:443 (Press CTRL+C to quit)
marzban  | WARNING:  Restarting Xray core...
marzban  | WARNING:  Xray core 24.12.31 started
marzban  | WARNING:  Restarting Xray core...
marzban  | WARNING:  Xray core 24.12.31 started
marzban  | WARNING:  Restarting Xray core...
marzban  | WARNING:  Xray core 24.12.31 started
marzban  | WARNING:  Restarting Xray core...
marzban  | WARNING:  Xray core 24.12.31 started
marzban  | WARNING:  Restarting Xray core...
```
