### ISSUE TITLE
502 BadGateway - Marzban + Traefik (Docker)

### ISSUE THREAD

**Issue by CryZFix** [Gozargah/Marzban#1836]
Do you have any recommendations and is it even possible to make friends with the current version of Marzban together with Traefik?

<details>
<summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/ac949189-866c-4d48-96ef-a7841fa543a8)

![Image](https://github.com/user-attachments/assets/20b53bdd-eee3-4a9b-b987-d37ec396d451)

</details>

**Machine details (please complete the following information):**
 - OS: Debian 12
 - Docker version 28.2.2, build e6534b4
 - Docker Compose version v2.36.2

**Additional context**

<details>
<summary>.env_marzban</summary>

```env
UVICORN_HOST=0.0.0.0

UVICORN_SSL_CERTFILE = "/var/lib/marzban/certs/marzban.domain.ru.crt"
UVICORN_SSL_KEYFILE = "/var/lib/marzban/certs/marzban.domain.ru.key"
```
</details>

<details>
<summary>docker-compose.yml</summary>

```yml
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik
      - "10000-10010:10000-10010"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Traefik (optional)
      - "traefik.http.routers.traefik.rule=Host(`traefik.domain.ru`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    env_file:
      - ./.env_marzban
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./traefik/certs:/var/lib/marzban/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # --- Роутер для панели Marzban (HTTPS) ---
      - "traefik.http.routers.marzban-secure.rule=Host(`marzban.domain.ru`)"
      - "traefik.http.routers.marzban-secure.entrypoints=websecure"
      - "traefik.http.routers.marzban-secure.tls=true"
      - "traefik.http.routers.marzban-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.marzban-secure.service=marzban-service"

      - "traefik.http.routers.marzban-http.rule=Host(`marzban.domain.ru`)"
      - "traefik.http.routers.marzban-http.entrypoints=web"
      - "traefik.http.routers.marzban-http.middlewares=https-redirect"

      - "traefik.http.services.marzban-service.loadbalancer.server.port=8000"

networks:
  proxy:
    name: proxy
```

</details>

<details>
<summary>traefik.yml</summary>

```yml
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "user@domain.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"
```

</details>

<details>
<summary>docker exec -it marzban curl -v localhost:8000</summary>

```bash

*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

```

</details>

<details>
<summary>docker exec -it marzban netstat -tulpn</summary>

```bash

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      1/python            
tcp        0      0 127.0.0.1:41236         0.0.0.0:*               LISTEN      32/xray             
tcp        0      0 127.0.0.11:40569        0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::1080                 :::*                    LISTEN      32/xray             
udp        0      0 127.0.0.11:53785        0.0.0.0:*                           -                   
udp6       0      0 :::1080                 :::*                                32/xray

```

</details>

<details>
<summary>docker exec -it traefik curl -v http://marzban:8000</summary>

```bash

* Host marzban:8000 was resolved.
* IPv6: (none)
* IPv4: 172.18.0.3
*   Trying 172.18.0.3:8000...
* Connected to marzban (172.18.0.3) port 8000
* using HTTP/1.x
> GET / HTTP/1.1
> Host: marzban:8000
> User-Agent: curl/8.12.1
> Accept: */*
> 
* abort upload
* Empty reply from server
* shutting down connection #0
curl: (52) Empty reply from server

```

</details>
