### ISSUE TITLE
باگ های تمپلیت کلش

### ISSUE THREAD

**Issue by tiredintps** [Gozargah/Marzban#319]
باگ ۱: فاصله اول خط در تمپلیت برداشته میشه
اگر در تمپلیت این مقادیر موجود باشند:
```yaml
rules:
  - DOMAIN-SUFFIX,1password.com,DIRECT
```
چیزی که درنهایت ساخته میشه این هست:
```yaml
rules:
- DOMAIN-SUFFIX,1password.com,DIRECT
```
که باعث میشه نظم فایل بهم بخوره و موجب باگ بشه

باگ۲: کانفیگ های vmess tcp http را شبکشون رو tcp در نظر میگیره
که این غلط هست و باید http در نظر بگیر
چیزی که باید خروجی دهد:
```yaml
rules:
  network: http
  http-opts:
    headers:
      Host: google.com
    method: GET
    path:
    - /
```
خروجی اشتباهش:
```yaml
rules:
  network: tcp
  tcp-opts:
    headers:
      Host: google.com
    method: GET
    path:
    - /
```
