### ISSUE TITLE
not generating clash config correctly 

### ISSUE THREAD

**Issue by hambn** [Gozargah/Marzban#560]
سلام و خسته نباشید
تو clash وقتی می خواد کانفیگ tcp + http header اضافه شه, غلط اضافه می کنه
مثلا اگه بخوایم این نوع کانفیگ رو با حالتی فعلی که اضافه می کنه, تو clash یا clash meta اضافه کنیم اینطوری میزنه 
```
- alterId: 0
  cipher: auto
  name: 'felan'
  network: tcp
  port: 8080
  server: felan.filan.com
  tcp-opts:
    headers:
      Host: felan.filan.com
    method: GET
    path:
    - /felan/filan
  type: vmess 
  udp: true
  uuid: felanfelan-felanfelan-felanfelan-felan
```

 که این غلطه و نباید اینطوری باشه و کار نمیکنه
درستش باید این باشه
```
- alterId: 0
  cipher: auto
  name: 'felan'
  network: http
  port: 1112
  server: felan.filan.com
  http-opts:
    Host: felan.filan.com
    method: GET
    path:
    - /felan/filan
  type: vmess 
  udp: true
  uuid: felanfelan-felanfelan-felanfelan-felan 
```
تا اینجا اینا باید تغییر 
### network 
> tcp -> http 

### opts
> tcp-opts -> http-opts
> ( headers: ) delete she

در کل ممنونم ازتون بابت زحماتی که میکشین
