### ISSUE TITLE
XTLS for VLESS and Domain Name Instead of Server IP

### ISSUE THREAD

**Issue by Moh3nGolshani** [Gozargah/Marzban#64]
Hi
Is it possible to use xtls for vless? (I tried to change it in xray_config.json but my dashboard will become unreachable).
Also is there anyway to set my domain name instead of my server IP when I create users? I know I can change it later in v2ray apps, but I want it as default.
Thanks in advance.

**Comment by meaqese** [comment]
Hi. xtls is deprecated and not recommended, yea u can use domains (edit XRAY_HOSTS in 0.1.0 version, in 0.2.0 u can edit it in dashboard),

**Comment by Moh3nGolshani** [comment]
Thanks
How to install version 0.2.0 using docker? I installed it yesterday but it was 0.1.0!

**Comment by meaqese** [comment]
@Moh3nGolshani 

Download this https://github.com/Gozargah/Marzban/archive/refs/heads/v0.2-0-dev.zip
Change Dockerfile to
```
FROM nikolaik/python-nodejs:python3.10-nodejs19-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt-get update \
    && apt-get install -y wget gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*
RUN wget -O - https://raw.githubusercontent.com/teddysun/across/master/docker/xray/xray.sh | bash \
    && ln -s /usr/bin/xray /usr/local/bin/xray \
    && mkdir -p /usr/local/share/xray/ \
    && wget -O /usr/local/share/xray/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat \
    && wget -O /usr/local/share/xray/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat

COPY . /code

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN apt-get remove -y wget gcc python3-dev

WORKDIR /code/app/dashboard
RUN npm i
WORKDIR /code

CMD ["bash", "-c", "alembic upgrade head; python main.py"]
```
Edit docker-compose.yml
```
services:
  marzban:
    build: .
    restart: on-failure
    env_file: env
    network_mode: host

    environment: # Change enviroment vars to ur own
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8880
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzban/db.sqlite3"
      XRAY_JSON: "/xray_config.json"
      XRAY_FALLBACKS_INBOUND_TAG: "TROJAN_FALLBACK_INBOUND" 

    volumes:
      - ./xray_config.json:/xray_config.json
      - /var/lib/marzban:/var/lib/marzban
```

After all up container, use `docker-compose up -d --build` cmnd.

But if you are not ready to deal with errors and do not know how to use Google or do not know how to read letters, then perhaps you should use the stable latest version 0.1.0 :)
